{% set name = "stable-baselines3" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stable_baselines3-{{ version }}.tar.gz
  sha256: 0b62b5148e8045c5d67f9f34d8de15c6248b325e15e5dcd931c88f236c735193

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cloudpickle
    - gymnasium==0.28.1
    - matplotlib-base
    - numpy >=1.20
    - pandas
    - python >=3.7
    - pytorch >=1.11

test:
  imports:
    - stable_baselines3
    - stable_baselines3.a2c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DLR-RM/stable-baselines3
  summary: Pytorch version of Stable Baselines, implementations of reinforcement learning algorithms.
  license: MIT
  license_file: LICENSE
  doc_url: https://stable-baselines3.readthedocs.io/
  dev_url: https://github.com/DLR-RM/stable-baselines3

extra:
  recipe-maintainers:
    - cyprienc
